services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: app
    command: ["./docker_compose/app.sh"]
    env_file:
      - ../.env
    ports:
      - "8080:8080"
    volumes:
      - ..:/code
    networks:
      - backend

volumes:
  ..:

networks:
  backend:
    driver: bridge